[package]
name = "trace"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Trace desktop clipping app"
authors.workspace = true

[lib]
# The `_lib` suffix keeps the lib name distinct from the bin name on Windows.
# https://github.com/rust-lang/cargo/issues/8519
name = "trace_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "tray-icon"] }
tauri-plugin-global-shortcut = "2"
tauri-plugin-notification = "2"
tauri-plugin-opener = "2"
tauri-plugin-process = "2"
tauri-plugin-updater = "2"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
crossbeam-channel.workspace = true
trace-engine = { path = "../crates/engine" }
trace-library = { path = "../crates/library" }
